"""Created User model

Revision ID: ce8be751be31
Revises: 65bfa1dd93a1
Create Date: 2025-05-29 06:23:57.581161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce8be751be31'
down_revision = '65bfa1dd93a1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
